{"stdout":"","stderr":"npm ERR! code ERESOLVE\nnpm ERR! ERESOLVE could not resolve\nnpm ERR! \nnpm ERR! While resolving: next-auth@5.0.0-beta.25\nnpm ERR! Found: next@15.2.0-canary.4\nnpm ERR! node_modules/next\nnpm ERR!   next@\"^15.2.0-canary.4\" from the root project\nnpm ERR!   peer overridden next@\"^15.2.0-canary.4\" (was \"^13.2.0 || ^14.0 || ^15.0.0-rc.0\") from @sentry/nextjs@8.49.0\nnpm ERR!   node_modules/@sentry/nextjs\nnpm ERR!     @sentry/nextjs@\"8\" from the root project\nnpm ERR! \nnpm ERR! Could not resolve dependency:\nnpm ERR! peer next@\"^14.0.0-0 || ^15.0.0-0\" from next-auth@5.0.0-beta.25\nnpm ERR! node_modules/next-auth\nnpm ERR!   next-auth@\"^5.0.0-beta.25\" from the root project\nnpm ERR! \nnpm ERR! Conflicting peer dependency: next@15.1.4\nnpm ERR! node_modules/next\nnpm ERR!   peer next@\"^14.0.0-0 || ^15.0.0-0\" from next-auth@5.0.0-beta.25\nnpm ERR!   node_modules/next-auth\nnpm ERR!     next-auth@\"^5.0.0-beta.25\" from the root project\nnpm ERR! \nnpm ERR! Fix the upstream dependency conflict, or retry\nnpm ERR! this command with --force or --legacy-peer-deps\nnpm ERR! to accept an incorrect (and potentially broken) dependency resolution.\nnpm ERR! \nnpm ERR! \nnpm ERR! For a full report see:\nnpm ERR! C:\\Users\\Admin\\AppData\\Local\\npm-cache\\_logs\\2025-01-15T10_38_10_576Z-eresolve-report.txt\n\nnpm ERR! A complete log of this run can be found in: C:\\Users\\Admin\\AppData\\Local\\npm-cache\\_logs\\2025-01-15T10_38_10_576Z-debug-0.log\n"}